acid: 酸洗
bodycon: 礼服
button: 有纽扣
capri: 卡普里布
chiffon: 雪纺衬衫
classic: 复古
collar: 领结
crochet: 钩编
crop: 裁剪针织
denim: 牛仔布
distressed: 破洞
dot: 圆点
drawstring: 拉绳
faux: 人造皮
faux fur: 人造皮
faux leather: 人造皮
floral: 碎花
floral print: 碎花
fur: 毛皮
graphic: 抽象图
hooded: 连帽
knit: 针织
lace: 花边
leather: 皮革
maxi: 马克西布
mini: 迷你布
muscle: 肌肉
paisley: 佩兹利布
pencil: 铅笔
plaid: 格子花呢
pleated: 打褶
pocket: 口袋
polka dot: 圆点
print: 印花
racerback: 运动背心
shirt: 衬衫
skater: 滑板装
skinny: 紧身
sleeve: 袖
sleeveless: 无袖
slim: 苗条
strapless: 露肩
stripe: 条纹
striped: 条纹
swim: 泳装
trench: 风衣
wash: 可水洗
zip: 拉链
