Anorak: 滑雪衫
Blazer: 西装外套
Blouse: 衬衫
Bomber: 皮衣
Button-Down: 衣领扣衬衫
Cardigan: 羊毛衣
Flannel: 绒布衫
Halter: 露背背心
Henley: 衣领扣T恤
Hoodie: 连帽衫
Jacket: 夹克
Jersey: 毛线衫
Parka: 大衣
Peacoat: 厚呢短大衣
Poncho: 披风
Sweater: 毛衣
Tank: 运动背心
Tee: T恤
Top: 上衣
Turtleneck: 高领毛衣
Capris: 中裤
Chinos: 斜纹棉布裤
Culottes: 裙裤
Cutoffs: 毛边短裤
Gauchos: 骑马服
Jeans: 牛仔裤
Jeggings: 牛仔打底裤
Jodhpurs: 马裤
Joggers: 宽松慢跑裤
Leggings: 紧身裤
Sarong: 纱笼
Shorts: 短裤
Skirt: 短裙
Sweatpants: 运动裤
Sweatshorts: 短裤
Trunks: 男用运动
Caftan: 长袖衣服
Cape: 斗篷
Coat: 外套
Coverup: 遮盖物
Dress: 连衣裙
Jumpsuit: 连身衣裤
Kaftan: 土耳其式长衫
Kimono: 和服
Nightdress: 睡衣
Onesie: 连帽衣
Robe: 长袍
Romper: 连身衣
Shirtdress: 衬衫裙
Sundress: 夏装
